bot:
  name: WerewolvessGameBot
  token: 6373757126:AAG9I9z8aDBFplXLThhl3fkJPasuadHs224
  start:
    description: Starts the bot
    text: Добро пожаловать в игру Оборотни.
  finish:
    description: Finish the bot
    text: Игра завершена

