bot:
  name: WerewolvessGameBot
  token: 6373757126:AAGWj4AbJXkXKqv-1Bu6oa9E3vGsvPtnVNM
  start:
    description: Starts the bot
    text: Добро пожаловать в игру Оборотни.
  finish:
    description: Finish the bot
    text: Игра завершена

